# Generated by Django 6.0 on 2026-03-12 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('gold', 'Gold'), ('reit', 'REIT'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Crypto'), ('cash', 'Cash / Liquid')], max_length=20)),
                ('asset_name', models.CharField(max_length=120)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('invested_amount', models.FloatField(default=0)),
                ('monthly_sip', models.FloatField(default=0)),
                ('current_value', models.FloatField(default=0)),
                ('annual_return_rate', models.FloatField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_value', '-id'],
            },
        ),
    ]
