# Generated by Django 6.0 on 2026-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investmentimportdocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='investmentimportdocument',
            new_name='investments_user_id_cbfa4c_idx',
            old_name='investmenti_user_id_a9ad33_idx',
        ),
        migrations.RenameIndex(
            model_name='investmentimportdocument',
            new_name='investments_user_id_9bfe43_idx',
            old_name='investmenti_user_id_359302_idx',
        ),
    ]
