# Generated by Django 6.0 on 2026-03-30 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=40)),
                ('service_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField(default=0)),
                ('service_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('oil_chain', 'Oil / Chain'), ('tyres', 'Tyres / Wheels'), ('accessory', 'Accessory / Upgrade'), ('custom', 'Custom Work')], default='routine', max_length=20)),
                ('cost', models.FloatField(default=0)),
                ('service_center', models.CharField(blank=True, max_length=160)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('next_service_km', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-service_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.FloatField(default=0)),
                ('transport_mode', models.CharField(choices=[('ride', 'Bike Ride'), ('roadtrip', 'Road Trip'), ('train', 'Train'), ('flight', 'Flight'), ('mixed', 'Mixed Mode')], default='ride', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('booked', 'Booked'), ('on_trip', 'On Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('stay_details', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('title', models.CharField(max_length=160)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0)),
                ('spend_amount', models.FloatField(default=0)),
                ('mood', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mobility.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='trip_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mobility.travelplan')),
                ('trip_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='mobility.triplog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at', '-id'],
            },
        ),
    ]
