# Generated by Django 6.0 on 2026-03-30 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('system', models.CharField(choices=[('general', 'General'), ('engine', 'Engine'), ('brakes', 'Brakes'), ('chain', 'Chain / Drive'), ('electrical', 'Electrical'), ('tyres', 'Tyres / Wheels'), ('suspension', 'Suspension'), ('clutch', 'Clutch / Gearbox'), ('body', 'Body / Accessories')], default='general', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('monitor', 'Monitor'), ('in_service', 'In Service'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('symptom', models.TextField()),
                ('observation', models.TextField(blank=True)),
                ('probable_cause', models.CharField(blank=True, max_length=220)),
                ('suggested_action', models.TextField(blank=True)),
                ('service_center_note', models.TextField(blank=True)),
                ('projected_cost', models.FloatField(default=0)),
                ('actual_cost', models.FloatField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to='mobility.bikeservicerecord')),
                ('travel_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bike_issue_reports', to='mobility.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at', '-id'],
            },
        ),
    ]
