# Generated by Django 6.0 on 2026-03-30 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0002_bikeissuereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeConditionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=40)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('overall_status', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('service', 'Service Soon'), ('urgent', 'Urgent')], default='good', max_length=20)),
                ('overall_score', models.PositiveIntegerField(default=80)),
                ('engine_status', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('service', 'Service Soon'), ('urgent', 'Urgent')], default='good', max_length=20)),
                ('brake_status', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('service', 'Service Soon'), ('urgent', 'Urgent')], default='good', max_length=20)),
                ('tyre_status', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('service', 'Service Soon'), ('urgent', 'Urgent')], default='good', max_length=20)),
                ('battery_status', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('service', 'Service Soon'), ('urgent', 'Urgent')], default='good', max_length=20)),
                ('body_status', models.CharField(choices=[('good', 'Good'), ('watch', 'Watch'), ('service', 'Service Soon'), ('urgent', 'Urgent')], default='good', max_length=20)),
                ('observed_symptoms', models.TextField(blank=True)),
                ('ai_assessment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_condition_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BikeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=40)),
                ('document_type', models.CharField(choices=[('insurance', 'Insurance'), ('puc', 'PUC'), ('registration', 'Registration / RC'), ('license', 'License'), ('roadside', 'Roadside Assistance'), ('invoice', 'Service Invoice'), ('other', 'Other')], default='other', max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('document_number', models.CharField(blank=True, max_length=120)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium_amount', models.FloatField(default=0)),
                ('verification_status', models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('incomplete', 'Incomplete')], default='incomplete', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('document_file', models.FileField(blank=True, upload_to='bike_documents/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', '-id'],
            },
        ),
    ]
