# Generated by Django 6.0 on 2026-03-30 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0003_bikeconditionsnapshot_bikedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bikedocument',
            name='document_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='extracted_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='parse_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='parser_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='parser_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikeservicerecord',
            name='extracted_work_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bikeservicerecord',
            name='parsed_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bikeservicerecord',
            name='source_document_name',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='bikeservicerecord',
            name='source_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('bill_import', 'Imported From Bill'), ('work_note', 'Imported From Work Note')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='BikeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=180)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=40)),
                ('bike_class', models.CharField(choices=[('commuter', 'Commuter'), ('roadster', 'Roadster'), ('retro', 'Retro'), ('adventure', 'Adventure'), ('sport', 'Sport'), ('cruiser', 'Cruiser'), ('scooter', 'Scooter'), ('touring', 'Touring'), ('custom', 'Custom')], default='roadster', max_length=20)),
                ('engine_cc', models.FloatField(blank=True, null=True)),
                ('fuel_tank_capacity_l', models.FloatField(blank=True, null=True)),
                ('expected_mileage_kmpl', models.FloatField(blank=True, null=True)),
                ('service_interval_km', models.PositiveIntegerField(blank=True, null=True)),
                ('service_interval_days', models.PositiveIntegerField(blank=True, null=True)),
                ('optimal_cruising_speed_kmph', models.PositiveIntegerField(blank=True, null=True)),
                ('tyre_front_spec', models.CharField(blank=True, max_length=40)),
                ('tyre_rear_spec', models.CharField(blank=True, max_length=40)),
                ('fuel_type', models.CharField(blank=True, default='petrol', max_length=20)),
                ('catalog_key', models.CharField(blank=True, max_length=80)),
                ('official_source_name', models.CharField(blank=True, max_length=120)),
                ('official_source_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('official', 'Official Catalog Match'), ('matched', 'AI Matched'), ('custom', 'Custom / Unverified')], default='custom', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('ai_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'display_name', '-updated_at'],
            },
        ),
    ]
