# Generated by Django 6.0 on 2026-03-30 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0004_bikedocument_document_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeconditionsnapshot',
            name='bike_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_snapshots', to='mobility.bikeprofile'),
        ),
        migrations.AddField(
            model_name='bikedocument',
            name='bike_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mobility.bikeprofile'),
        ),
        migrations.AddField(
            model_name='bikeissuereport',
            name='bike_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_reports', to='mobility.bikeprofile'),
        ),
        migrations.AddField(
            model_name='bikeprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('scooter', 'Scooter'), ('car', 'Car'), ('other', 'Other')], default='motorcycle', max_length=20),
        ),
        migrations.AddField(
            model_name='bikeservicerecord',
            name='bike_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='mobility.bikeprofile'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='vehicle_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='travel_plans', to='mobility.bikeprofile'),
        ),
        migrations.AlterField(
            model_name='bikeprofile',
            name='bike_class',
            field=models.CharField(choices=[('commuter', 'Commuter'), ('roadster', 'Roadster'), ('retro', 'Retro'), ('adventure', 'Adventure'), ('sport', 'Sport'), ('cruiser', 'Cruiser'), ('scooter', 'Scooter'), ('touring', 'Touring'), ('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('mpv', 'MPV'), ('custom', 'Custom')], default='roadster', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bikeconditionsnapshot',
            index=models.Index(fields=['user', 'bike_profile', 'captured_at'], name='mobility_bi_user_id_6031ab_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeconditionsnapshot',
            index=models.Index(fields=['user', 'vehicle_number', 'captured_at'], name='mobility_bi_user_id_19ac1b_idx'),
        ),
        migrations.AddIndex(
            model_name='bikedocument',
            index=models.Index(fields=['user', 'bike_profile', 'document_type', 'expiry_date'], name='mobility_bi_user_id_0d0660_idx'),
        ),
        migrations.AddIndex(
            model_name='bikedocument',
            index=models.Index(fields=['user', 'vehicle_number', 'document_type'], name='mobility_bi_user_id_8e70bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeissuereport',
            index=models.Index(fields=['user', 'bike_profile', 'status', 'reported_at'], name='mobility_bi_user_id_aeaa0b_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeissuereport',
            index=models.Index(fields=['user', 'severity', 'status', 'reported_at'], name='mobility_bi_user_id_949667_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeprofile',
            index=models.Index(fields=['user', 'vehicle_type', 'is_primary'], name='mobility_bi_user_id_40ce0f_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeprofile',
            index=models.Index(fields=['user', 'display_name'], name='mobility_bi_user_id_145fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeprofile',
            index=models.Index(fields=['user', 'vehicle_number'], name='mobility_bi_user_id_51b166_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeservicerecord',
            index=models.Index(fields=['user', 'bike_profile', 'service_date'], name='mobility_bi_user_id_26516d_idx'),
        ),
        migrations.AddIndex(
            model_name='bikeservicerecord',
            index=models.Index(fields=['user', 'vehicle_number', 'service_date'], name='mobility_bi_user_id_c7812c_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user', 'status', 'start_date'], name='mobility_tr_user_id_9b4e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['user', 'vehicle_profile', 'start_date'], name='mobility_tr_user_id_f32f77_idx'),
        ),
        migrations.AddIndex(
            model_name='triplog',
            index=models.Index(fields=['user', 'travel_plan', 'log_date'], name='mobility_tr_user_id_0f2617_idx'),
        ),
        migrations.AddIndex(
            model_name='tripphoto',
            index=models.Index(fields=['user', 'travel_plan', 'taken_at'], name='mobility_tr_user_id_b78d6f_idx'),
        ),
    ]
