# Generated by Django 6.0 on 2026-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0005_bikeconditionsnapshot_bike_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeprofile',
            name='estimated_market_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikeprofile',
            name='monthly_income_support',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bikeprofile',
            name='usage_pattern',
            field=models.CharField(choices=[('personal', 'Personal / Lifestyle'), ('essential', 'Essential Mobility'), ('mixed', 'Mixed Personal + Utility'), ('commercial', 'Commercial / Income Generating')], default='personal', max_length=20),
        ),
    ]
