# Generated by Django 6.0 on 2026-03-30 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0006_bikeprofile_estimated_market_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRefillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=120)),
                ('vehicle_number', models.CharField(blank=True, max_length=40)),
                ('refill_date', models.DateField()),
                ('odometer_km', models.PositiveIntegerField(blank=True, null=True)),
                ('trip_meter_km', models.FloatField(default=0)),
                ('fuel_liters', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('is_full_tank', models.BooleanField(default=True)),
                ('station_name', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_refill_logs', to='mobility.bikeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_refill_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-refill_date', '-id'],
                'indexes': [models.Index(fields=['user', 'bike_profile', 'refill_date'], name='mobility_fu_user_id_5019fc_idx'), models.Index(fields=['user', 'vehicle_number', 'refill_date'], name='mobility_fu_user_id_00dfeb_idx')],
            },
        ),
    ]
