# Generated by Django 6.0 on 2026-09-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0008_bikeservicerecord_source_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='itinerary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='planning_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='ignored_plan_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripphoto',
            name='preference_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('researching', 'Researching'), ('suggestions_ready', 'Suggestions Ready'), ('planned', 'Planned'), ('confirmed', 'Confirmed'), ('booked', 'Booked'), ('on_trip', 'On Trip'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='tripphoto',
            name='travel_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mobility.travelplan'),
        ),
        migrations.CreateModel(
            name='TravelFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('loved', 'Loved it'), ('good', 'Good'), ('okay', 'Okay'), ('disliked', "Didn't enjoy it")], max_length=20)),
                ('liked', models.JSONField(default=list)),
                ('disliked', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='mobility.travelplan')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Your next escape', max_length=160)),
                ('state', models.JSONField(default=dict)),
                ('candidates', models.JSONField(default=list)),
                ('itinerary', models.JSONField(default=dict)),
                ('status', models.CharField(default='discovery', max_length=30)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_session', to='mobility.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Alfred')], max_length=12)),
                ('text', models.TextField()),
                ('chips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mobility.travelplanningsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TravelPreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelty', models.CharField(choices=[('mostly_new', 'Mostly New'), ('balanced', 'Balanced'), ('mostly_familiar', 'Mostly Familiar')], default='balanced', max_length=20)),
                ('preferences', models.JSONField(default=dict)),
                ('learning_enabled', models.BooleanField(default=True)),
                ('media_learning_enabled', models.BooleanField(default=False)),
                ('reset_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='queued', max_length=40)),
                ('deep', models.BooleanField(default=False)),
                ('recheck', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('research_version', models.PositiveIntegerField(default=1)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('sources_checked', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('changes', models.JSONField(default=list)),
                ('result', models.JSONField(default=list)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='mobility.travelplanningsession')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TravelResearchEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=40)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_name', models.CharField(max_length=160)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.CharField(default='UNKNOWN', max_length=16)),
                ('freshness', models.CharField(default='unknown', max_length=20)),
                ('finding', models.JSONField(default=dict)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='mobility.travelresearchsession')),
            ],
        ),
    ]
