# Generated by Django 6.0 on 2026-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0009_travelplan_itinerary_travelplan_planning_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelProviderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=80, unique=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('next_allowed_at', models.DateTimeField(blank=True, null=True)),
                ('quota_remaining', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='travelresearchevidence',
            name='error',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='travelresearchevidence',
            name='provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='travelresearchevidence',
            name='request_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='travelresearchevidence',
            name='response_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='travelresearchevidence',
            name='status',
            field=models.CharField(default='unverified', max_length=32),
        ),
        migrations.AddField(
            model_name='travelresearchevidence',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TravelProviderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(max_length=40)),
                ('cache_key', models.CharField(max_length=160)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=32)),
                ('network_call', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'created_at'], name='travel_provider_time_idx')],
            },
        ),
    ]
