# Generated by Django 6.0 on 2026-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobility', '0011_destination_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='transport_mode',
            field=models.CharField(choices=[('ride', 'Bike Ride'), ('roadtrip', 'Road Trip'), ('train', 'Train'), ('bus', 'Bus'), ('flight', 'Flight'), ('mixed', 'Mixed Mode')], default='ride', max_length=20),
        ),
    ]
