# Generated by Django 6.0 on 2026-03-30 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', models.CharField(choices=[('CIBIL', 'TransUnion CIBIL'), ('EXPERIAN', 'Experian'), ('EQUIFAX', 'Equifax'), ('CRIF', 'CRIF High Mark')], max_length=20)),
                ('score', models.IntegerField()),
                ('score_range_min', models.IntegerField(default=300)),
                ('score_range_max', models.IntegerField(default=900)),
                ('rating', models.CharField(max_length=20)),
                ('total_accounts', models.IntegerField(default=0)),
                ('active_accounts', models.IntegerField(default=0)),
                ('closed_accounts', models.IntegerField(default=0)),
                ('delinquent_accounts', models.IntegerField(default=0)),
                ('total_credit_limit', models.FloatField(default=0)),
                ('credit_utilization', models.FloatField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditScoreFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('score', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('credit_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='integrations.creditscore')),
            ],
            options={
                'ordering': ['-weight'],
            },
        ),
        migrations.CreateModel(
            name='EmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GMAIL', 'Gmail'), ('OUTLOOK', 'Outlook / Microsoft 365'), ('IMAP', 'Generic IMAP')], max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('auto_import_enabled', models.BooleanField(default=True)),
                ('sync_frequency_days', models.IntegerField(default=7)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='creditscore',
            index=models.Index(fields=['user', 'bureau', '-fetched_at'], name='integration_user_id_a2c859_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailconnection',
            unique_together={('user', 'email_address')},
        ),
    ]
