# Generated by Django 6.0 on 2026-03-30 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedExternalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('cache_key', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=180)),
                ('source_name', models.CharField(max_length=180)),
                ('source_url', models.URLField()),
                ('query', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('stale', 'Stale'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='fresh', max_length=20)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stale_after', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_external_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified_at', '-id'],
                'indexes': [models.Index(fields=['scope', 'cache_key', 'status'], name='integration_scope_1cff85_idx'), models.Index(fields=['user', 'scope', 'cache_key'], name='integration_user_id_72aebd_idx'), models.Index(fields=['stale_after', 'status'], name='integration_stale_a_82c339_idx')],
            },
        ),
    ]
