# Generated by Django 6.0 on 2026-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_verifiedexternalinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscore',
            name='score_kind',
            field=models.CharField(choices=[('estimated', 'Estimated From Alfred Data'), ('official', 'Official Bureau Pull')], default='estimated', max_length=20),
        ),
    ]
