# Generated by Django 6.0 on 2026-03-30 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_creditscore_score_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReportUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='credit_reports/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('bureau', models.CharField(blank=True, choices=[('CIBIL', 'TransUnion CIBIL'), ('EXPERIAN', 'Experian'), ('EQUIFAX', 'Equifax'), ('CRIF', 'CRIF High Mark')], max_length=20)),
                ('parser_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_confidence', models.FloatField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('parser_notes', models.TextField(blank=True)),
                ('applicant_name', models.CharField(blank=True, max_length=180)),
                ('report_number', models.CharField(blank=True, max_length=120)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parsed_credit_score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_upload', to='integrations.creditscore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_report_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'bureau', 'created_at'], name='integration_user_id_b17a88_idx'), models.Index(fields=['user', 'parser_status', 'created_at'], name='integration_user_id_0f447c_idx')],
            },
        ),
    ]
