# Generated by Django 6.0 on 2026-08-09 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code_hash', models.CharField(max_length=64, unique=True)),
                ('invite_code_hint', models.CharField(blank=True, max_length=16)),
                ('share_profile_summary', models.BooleanField(default=True)),
                ('share_dependents', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_link_invites', to=settings.AUTH_USER_MODEL)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_link_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_by', 'status', 'expires_at'], name='family_fami_created_d7efe1_idx'), models.Index(fields=['linked_user', 'status'], name='family_fami_linked__d65dd9_idx'), models.Index(fields=['status', 'expires_at'], name='family_fami_status_d46e86_idx')],
            },
        ),
    ]
