# Generated by Django 6.0 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("family", "0002_familyaccountlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="familyaccountlink",
            name="share_financial_summary",
            field=models.BooleanField(default=True),
        ),
    ]
