from django.urls import path

from .views import (
    BikeConditionSnapshotDetailView,
    BikeConditionSnapshotListCreateView,
    BikeDocumentDetailView,
    BikeDocumentListCreateView,
    BikeDocumentUploadView,
    BikeIssueReportDetailView,
    BikeIssueReportListCreateView,
    BikeModelCatalogView,
    BikeProfileDetailView,
    BikeProfileListCreateView,
    FuelRefillLogDetailView,
    FuelRefillLogListCreateView,
    BikeServiceImportView,
    BikeServiceDashboardView,
    BikeServiceRecordDetailView,
    BikeServiceRecordListCreateView,
    MobilityDashboardView,
    TravelAdvisorPreviewView,
    TravelPlanDetailView,
    TravelPlanListCreateView,
    TripLogDetailView,
    TripLogListCreateView,
    TripPhotoDetailView,
    TripPhotoListCreateView,
)

urlpatterns = [
    path("dashboard/", MobilityDashboardView.as_view(), name="mobility_dashboard"),
    path("bike-service-dashboard/", BikeServiceDashboardView.as_view(), name="bike_service_dashboard"),
    path("bike-models/catalog/", BikeModelCatalogView.as_view(), name="bike_model_catalog"),
    path("bikes/", BikeProfileListCreateView.as_view(), name="bike_profile_list"),
    path("bikes/<int:pk>/", BikeProfileDetailView.as_view(), name="bike_profile_detail"),
    path("bike-services/", BikeServiceRecordListCreateView.as_view(), name="bike_service_list"),
    path("bike-refills/", FuelRefillLogListCreateView.as_view(), name="fuel_refill_list"),
    path("bike-refills/<int:pk>/", FuelRefillLogDetailView.as_view(), name="fuel_refill_detail"),
    path("bike-services/import/", BikeServiceImportView.as_view(), name="bike_service_import"),
    path("bike-services/<int:pk>/", BikeServiceRecordDetailView.as_view(), name="bike_service_detail"),
    path("bike-issues/", BikeIssueReportListCreateView.as_view(), name="bike_issue_list"),
    path("bike-issues/<int:pk>/", BikeIssueReportDetailView.as_view(), name="bike_issue_detail"),
    path("bike-documents/", BikeDocumentListCreateView.as_view(), name="bike_document_list"),
    path("bike-documents/upload/", BikeDocumentUploadView.as_view(), name="bike_document_upload"),
    path("bike-documents/<int:pk>/", BikeDocumentDetailView.as_view(), name="bike_document_detail"),
    path("bike-conditions/", BikeConditionSnapshotListCreateView.as_view(), name="bike_condition_list"),
    path("bike-conditions/<int:pk>/", BikeConditionSnapshotDetailView.as_view(), name="bike_condition_detail"),
    path("travel-advisor/preview/", TravelAdvisorPreviewView.as_view(), name="travel_advisor_preview"),
    path("travel-plans/", TravelPlanListCreateView.as_view(), name="travel_plan_list"),
    path("travel-plans/<int:pk>/", TravelPlanDetailView.as_view(), name="travel_plan_detail"),
    path("trip-logs/", TripLogListCreateView.as_view(), name="trip_log_list"),
    path("trip-logs/<int:pk>/", TripLogDetailView.as_view(), name="trip_log_detail"),
    path("trip-photos/", TripPhotoListCreateView.as_view(), name="trip_photo_list"),
    path("trip-photos/<int:pk>/", TripPhotoDetailView.as_view(), name="trip_photo_detail"),
]
