# Generated by Django 6.0 on 2026-03-31 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('training', 'Training'), ('ready', 'Ready'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('last_trigger', models.CharField(blank=True, max_length=32)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('confidence_estimate', models.FloatField(default=0)),
                ('artifact_path', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('freshness_hours', models.PositiveIntegerField(default=24)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_refresh_due_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name', 'model_key'],
            },
        ),
        migrations.CreateModel(
            name='AdaptiveTrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=120)),
                ('trigger', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('training', 'Training'), ('ready', 'Ready'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='idle', max_length=20)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('confidence_estimate', models.FloatField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['model_key', 'started_at'], name='ml_engine_a_model_k_6b3fdf_idx'), models.Index(fields=['status', 'started_at'], name='ml_engine_a_status_83cf28_idx')],
            },
        ),
    ]
