# Generated by Django 6.0 on 2026-03-31 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentParserLearningMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('file_extension', models.CharField(max_length=16)),
                ('detected_type', models.CharField(blank=True, max_length=60)),
                ('template_signature', models.CharField(blank=True, max_length=255)),
                ('field_signature', models.CharField(blank=True, max_length=255)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0)),
                ('observed_fields', models.JSONField(blank=True, default=list)),
                ('observed_keywords', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_parser_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['user', 'scope', 'file_extension'], name='ml_engine_d_user_id_f59ad3_idx'), models.Index(fields=['user', 'scope', 'detected_type'], name='ml_engine_d_user_id_7899d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scope', 'file_extension', 'detected_type', 'template_signature', 'field_signature'), name='ml_engine_document_parser_learning_unique_key')],
            },
        ),
    ]
