# Generated by Django 6.0 on 2026-04-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ml_training_consent_given_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="ml_training_consent_granted",
            field=models.BooleanField(default=False),
        ),
    ]
