from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
import re
from typing import BinaryIO

from pypdf import PdfReader


TXN_START_RE = re.compile(r"^\d{2}/\d{2}/\d{2}\s+")
TXN_RE = re.compile(
    r"^(?P<txn_date>\d{2}/\d{2}/\d{2})\s+"
    r"(?P<body>.+?)\s+"
    r"(?P<value_date>\d{2}/\d{2}/\d{2})\s+"
    r"(?P<amount>[0-9,]+\.\d{2})\s+"
    r"(?P<closing>[0-9,]+\.\d{2})"
    r"(?:\s+(?P<tail>.*))?$"
)
PERIOD_RE = re.compile(r"Statement of accountFrom : (\d{2}/\d{2}/\d{4}) To : (\d{2}/\d{2}/\d{4})")
ACCOUNT_NO_RE = re.compile(r"Account No : ([0-9A-Z ]+)")
ACCOUNT_HOLDER_RE = re.compile(r"MR ([A-Z ]+)")
REFERENCE_RE = re.compile(r"\b[A-Z0-9]{10,}\b")

HEADER_PREFIXES = (
    "Page No",
    "MR ",
    "JOINT HOLDERS",
    "Nomination",
    "Statement of accountFrom",
    "Account Branch",
    "Address",
    "City",
    "State",
    "Phone no.",
    "OD Limit",
    "Currency",
    "Email",
    "Cust ID",
    "Account No",
    "A/C Open Date",
    "Account Status",
    "RTGS/NEFT IFSC",
    "Branch Code",
    "Account Type",
    "HDFC BANK LIMITED",
    "*Closing balance",
    "Contents of this statement",
    "State account branch GSTN",
    "HDFC Bank GSTIN",
    "Registered Office Address",
    "Date Narration",
)

PAYMENT_MODE_RULES = [
    ("UPI", "UPI"),
    ("ACH D", "ACH"),
    ("NEFT CR", "NEFT"),
    ("RTGS CR", "RTGS"),
    ("IMPS CR", "IMPS"),
    ("ATM", "ATM"),
    ("POS", "CARD"),
    ("CARD", "CARD"),
]

NOISE_MARKERS = (
    "STATEMENT SUMMARY",
    "Generated On:",
    "Generated By:",
    "This is a computer generated statement",
    "Opening Balance",
)

KNOWN_MERCHANT_RULES = [
    (("SWIGGY",), "Swiggy"),
    (("ZOMATO", "ETERNAL"), "Zomato"),
    (("JIO PREPAID RECHARGE",), "Jio Prepaid Recharge"),
    (("CRED CLUB", "PAYMENT ON CRED", "RAZPCREDCLUB"), "CRED Club"),
    (("ONECARD",), "OneCard"),
    (("AMAZON",), "Amazon"),
    (("FLIPKART",), "Flipkart"),
    (("MYNTRA",), "Myntra"),
    (("SMART BAZAAR",), "Smart Bazaar"),
    (("NOBROKER",), "NoBroker"),
]

MERCHANT_NOISE_PATTERNS = (
    r"\bPAID\s+V\s*IA\s+CRED\b",
    r"\bPAYMENT\s+ON\s+CRED\b",
    r"\bPAY\s+FOR\s+INTENT\b",
    r"\bIN\s+APP\b",
    r"\bREMARKS\b.*$",
    r"\bSTATEMENT\s+SUMMARY\b.*$",
)

CLASSIFICATION_RULES = [
    ("loan", "loan", ("BAJAJ HOUSING", "POONAWALLA", "FINCOR", "EMI", "LOAN", "H404HHL", "FINANC", "PLA")),
    ("other", "investment", ("GROWW", "ZERODHA", "MUTUAL FUND", "STOCK", "MF ")),
    ("expense", "groceries", ("GROCERY", "SUPERMARKET", "SMART BAZAAR")),
    ("expense", "food", ("CAFE", "BAKERY", "HOTEL", "RESTAURANT", "SWIGGY", "ZOMATO", "FOOD")),
    ("expense", "health", ("DENTAL", "PHARMA", "HOSPITAL", "CLINIC", "MEDICAL")),
    ("expense", "fuel", ("FILLING STATIO", "PETROL", "FUEL", "HPCL", "IOCL", "BPCL", "INDIAN OIL")),
    ("expense", "utilities", ("ELECTRICIT", "RECHARGE", "PAYMENTFORBILLS", "BILL", "WATER", "GAS")),
    ("expense", "subscription", ("GOOGLE PLAY", "PLAYSTORE", "NETFLIX", "SPOTIFY", "PRIME", "YOUTUBE")),
    ("expense", "shopping", ("AMAZON", "MYNTRA", "FLIPKART", "SHOP", "NOBROKER")),
    ("expense", "travel", ("UBER", "OLA", "METRO", "IRCTC", "AUTOMOB")),
    ("other", "credit_card", ("ONECARD", "CRED CLUB", "PAYMENT ON CRED", "RAZPCREDCLUB", "CREDIT CARD")),
]
BANK_NAME_RULES = [
    ("HDFC BANK", "HDFC Bank"),
    ("ICICI BANK", "ICICI Bank"),
    ("STATE BANK OF INDIA", "State Bank of India"),
    ("AXIS BANK", "Axis Bank"),
    ("KOTAK", "Kotak Mahindra Bank"),
]
STATEMENT_KIND_RULES = [
    ("credit_card_statement", ("CREDIT CARD", "CARD STATEMENT", "TOTAL AMOUNT DUE", "MINIMUM AMOUNT DUE", "PAYMENT DUE DATE")),
    ("loan_statement", ("LOAN STATEMENT", "REPAYMENT SCHEDULE", "SANCTION LETTER", "DISBURSEMENT", "EMI AMOUNT", "AMORTIZATION")),
    ("investment_statement", ("PORTFOLIO", "HOLDINGS STATEMENT", "MUTUAL FUND", "DEMAT", "BROKERAGE", "CONTRACT NOTE")),
]
LOAN_TYPE_HINT_RULES = [
    ("home", ("HOME LOAN", "HOUSING LOAN", "HHL")),
    ("personal", ("PERSONAL LOAN", "PL ")),
    ("car", ("CAR LOAN", "AUTO LOAN", "VEHICLE LOAN")),
    ("education", ("EDUCATION LOAN", "STUDENT LOAN")),
    ("business", ("BUSINESS LOAN",)),
    ("credit_card", ("CREDIT CARD",)),
]


@dataclass
class ParsedTransaction:
    transaction_date: date
    amount: float
    closing_balance: float
    direction: str
    classification: str
    category: str
    payment_mode: str
    merchant: str
    description: str
    raw_description: str
    external_reference: str
    counterparty: str
    company_name: str


@dataclass
class StatementParseResult:
    bank_name: str
    account_holder: str
    account_number: str
    statement_start: date | None
    statement_end: date | None
    transactions: list[ParsedTransaction]
    statement_kind: str
    parser_status: str
    confidence: float
    source_text: str
    loan_hints: dict


def parse_bank_statement(file_obj: BinaryIO) -> StatementParseResult:
    reader = PdfReader(file_obj)
    pages = [page.extract_text() or "" for page in reader.pages]
    full_text = "\n".join(pages)

    bank_name = _extract_bank_name(full_text)
    account_holder = _extract_account_holder(full_text)
    account_number = _extract_account_number(full_text)
    statement_start, statement_end = _extract_statement_period(full_text)
    statement_kind = _detect_statement_kind(full_text)
    loan_hints = _extract_loan_hints(full_text)

    groups = _collect_transaction_groups(full_text.splitlines())
    transactions: list[ParsedTransaction] = []
    previous_closing: float | None = None

    for group in groups:
        transaction = _parse_transaction_group(group, previous_closing)
        if transaction is None:
            continue
        transactions.append(transaction)
        previous_closing = transaction.closing_balance

    confidence = 0.45
    if full_text.strip():
        confidence += 0.15
    if bank_name:
        confidence += 0.1
    if account_number:
        confidence += 0.1
    if transactions:
        confidence += 0.25
    elif statement_kind != "other_statement":
        confidence += 0.05
    confidence = round(min(confidence, 0.97), 2)
    parser_status = "parsed" if transactions else ("needs_review" if full_text.strip() else "failed")

    return StatementParseResult(
        bank_name=bank_name,
        account_holder=account_holder,
        account_number=account_number,
        statement_start=statement_start,
        statement_end=statement_end,
        transactions=transactions,
        statement_kind=statement_kind,
        parser_status=parser_status,
        confidence=confidence,
        source_text=full_text[:20000],
        loan_hints=loan_hints,
    )


def summarize_transactions(transactions: list[ParsedTransaction]) -> dict[str, float | int]:
    summary = {
        "expense_total": 0.0,
        "loan_total": 0.0,
        "other_total": 0.0,
        "income_total": 0.0,
        "transaction_count": len(transactions),
    }

    for item in transactions:
        if item.direction == "credit":
            summary["income_total"] += item.amount
            continue

        if item.classification == "expense":
            summary["expense_total"] += item.amount
        elif item.classification == "loan":
            summary["loan_total"] += item.amount
        else:
            summary["other_total"] += item.amount

    return summary


def _collect_transaction_groups(lines: list[str]) -> list[str]:
    groups: list[str] = []
    current: list[str] = []

    for raw_line in lines:
        line = _normalize_space(raw_line)
        if not line or _is_statement_header(line):
            continue

        if TXN_START_RE.match(line):
            if current:
                groups.append(" ".join(current))
            current = [line]
            continue

        if current:
            current.append(line)

    if current:
        groups.append(" ".join(current))

    return groups


def _parse_transaction_group(group: str, previous_closing: float | None) -> ParsedTransaction | None:
    match = TXN_RE.search(_normalize_space(group))
    if match is None:
        return None

    description = match.group("body")
    if match.group("tail"):
        description = f"{description} {match.group('tail')}"
    details = classify_transaction_text(description, _infer_direction(description, _to_float(match.group("closing")), previous_closing))
    amount = _to_float(match.group("amount"))
    closing_balance = _to_float(match.group("closing"))
    direction = details["direction"]

    return ParsedTransaction(
        transaction_date=datetime.strptime(match.group("value_date"), "%d/%m/%y").date(),
        amount=amount,
        closing_balance=closing_balance,
        direction=details["direction"],
        classification=details["classification"],
        category=details["category"],
        payment_mode=details["payment_mode"],
        merchant=details["merchant"],
        description=details["description"],
        raw_description=details["raw_description"],
        external_reference=details["external_reference"],
        counterparty=details["counterparty"],
        company_name=details["company_name"],
    )


def classify_transaction_text(description: str, direction: str) -> dict[str, str]:
    cleaned = _sanitize_description(description)
    normalized_direction = _infer_direction(cleaned, 0, None) if direction not in {"credit", "debit"} else direction
    classification, category = _classify_transaction(cleaned, normalized_direction)

    return {
        "direction": normalized_direction,
        "classification": classification,
        "category": category,
        "payment_mode": _infer_payment_mode(cleaned),
        "merchant": _extract_merchant(cleaned),
        "description": _build_description(cleaned, classification, category),
        "raw_description": cleaned,
        "external_reference": _extract_reference(cleaned),
        "counterparty": _extract_merchant(cleaned),
        "company_name": _extract_company_name(cleaned),
    }


def _classify_transaction(description: str, direction: str) -> tuple[str, str]:
    text = description.upper()

    if direction == "credit":
        if any(keyword in text for keyword in ("REFUND", "REVERSAL", "REVERSED")):
            return "other", "income"
        if any(keyword in text for keyword in ("NEFT CR", "RTGS CR", "IMPS CR", "SALARY", "BONUS")):
            return "other", "income"
        return "other", "transfer"

    for classification, category, keywords in CLASSIFICATION_RULES:
        if any(keyword in text for keyword in keywords):
            return classification, category

    if any(token in text for token in ("@YBL", "@OKAXIS", "@AXIS", "@PTY", "@YESPAY")):
        return "other", "transfer"

    return "expense", "other"


def _infer_direction(description: str, closing_balance: float, previous_closing: float | None) -> str:
    text = description.upper()

    if previous_closing is not None:
        if closing_balance > previous_closing:
            return "credit"
        if closing_balance < previous_closing:
            return "debit"

    if any(keyword in text for keyword in (" CR", " REFUND", "REVERSAL", "SALARY", "NEFT CR", "RTGS CR", "IMPS CR")):
        return "credit"

    return "debit"


def _infer_payment_mode(description: str) -> str:
    text = description.upper()
    for prefix, payment_mode in PAYMENT_MODE_RULES:
        if text.startswith(prefix):
            return payment_mode
    return "BANK"


def _extract_merchant(description: str) -> str:
    text = description.upper()
    known_merchant = _match_known_merchant(text)
    if known_merchant:
        return known_merchant

    pieces = re.split(r"[-/]", text)
    merchant_parts: list[str] = []

    for piece in pieces:
        value = _clean_merchant_piece(piece)
        if not value:
            continue
        if any(char.isdigit() for char in value) and len(value.replace(" ", "")) > 8:
            continue
        if value in {"UPI", "ACH D", "NEFT CR", "RTGS CR", "IMPS CR", "PAY", "UPI PAY"}:
            continue
        if value.startswith(("YESB", "UTIB", "HDFC", "ICIC", "KKBK", "FDRL", "AIRP", "RZP")):
            continue
        merchant_parts.append(value.title())
        if len(" ".join(merchant_parts)) >= 40:
            break

    if merchant_parts:
        return " ".join(merchant_parts[:3])

    return description[:60].title()


def _build_description(raw_description: str, classification: str, category: str) -> str:
    cleaned = raw_description.strip()
    if classification == "loan":
        return f"Auto-classified as loan payment: {cleaned[:140]}"
    if category == "credit_card":
        return f"Auto-classified as credit card payment: {cleaned[:140]}"
    if category == "investment":
        return f"Auto-classified as investment transfer: {cleaned[:140]}"
    return cleaned[:140]


def _extract_reference(description: str) -> str:
    matches = REFERENCE_RE.findall(description.upper())
    if not matches:
        return ""
    return matches[-1]


def _extract_statement_period(full_text: str) -> tuple[date | None, date | None]:
    match = PERIOD_RE.search(full_text)
    if match is None:
        return None, None
    return (
        datetime.strptime(match.group(1), "%d/%m/%Y").date(),
        datetime.strptime(match.group(2), "%d/%m/%Y").date(),
    )


def _extract_account_number(full_text: str) -> str:
    match = ACCOUNT_NO_RE.search(full_text)
    if match is None:
        return ""
    return _normalize_space(match.group(1))


def _extract_account_holder(full_text: str) -> str:
    match = ACCOUNT_HOLDER_RE.search(full_text)
    if match is None:
        return ""
    return _normalize_space(match.group(1).title())


def _extract_bank_name(full_text: str) -> str:
    text = full_text.upper()
    for keyword, label in BANK_NAME_RULES:
        if keyword in text:
            return label
    match = re.search(r"([A-Z ]+BANK(?: LIMITED)?)", text)
    if match is None:
        return ""
    return _normalize_space(match.group(1).title())


def _detect_statement_kind(full_text: str) -> str:
    text = full_text.upper()
    for statement_kind, keywords in STATEMENT_KIND_RULES:
        if any(keyword in text for keyword in keywords):
            return statement_kind
    if any(keyword in text for keyword in ("STATEMENT OF ACCOUNT", "ACCOUNT NO", "CLOSING BALANCE")):
        return "bank_statement"
    return "other_statement"


def _extract_loan_hints(full_text: str) -> dict:
    text = full_text.upper()
    inferred_type = ""
    for loan_type, keywords in LOAN_TYPE_HINT_RULES:
        if any(keyword in text for keyword in keywords):
            inferred_type = loan_type
            break

    lender = _extract_bank_name(full_text)
    match = re.search(r"(?:EMI|INSTALLMENT)\s+(?:AMOUNT|AMT)?\s*[:.]?\s*(?:INR|RS\.?)?\s*([0-9,]+(?:\.\d{2})?)", text)
    emi_amount = float(match.group(1).replace(",", "")) if match else 0.0

    return {
        "loan_type": inferred_type,
        "lender": lender,
        "emi_amount": emi_amount,
    }


def _is_statement_header(line: str) -> bool:
    if line == ".":
        return True
    return line.startswith(HEADER_PREFIXES)


def _normalize_space(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def _sanitize_description(value: str) -> str:
    cleaned = _normalize_space(value)
    for marker in NOISE_MARKERS:
        if marker in cleaned:
            cleaned = cleaned.split(marker, 1)[0].strip()
    return _normalize_space(cleaned)


def _to_float(value: str) -> float:
    return float(value.replace(",", ""))


def _match_known_merchant(text: str) -> str:
    if "INDIAN OIL" in text:
        return "Indian Oil Petrol Pump"

    filling_station = re.search(r"(?:UPI-)?([A-Z0-9 ]+FILLING STATIO)", text)
    if filling_station:
        return filling_station.group(1).replace("STATIO", "Station").title()

    for keywords, merchant in KNOWN_MERCHANT_RULES:
        if any(keyword in text for keyword in keywords):
            return merchant

    return ""


def _extract_company_name(text: str) -> str:
    merchant = _match_known_merchant(text)
    if merchant:
        return merchant

    upper = text.upper()
    for keyword, label in BANK_NAME_RULES:
        if keyword in upper:
            return label
    for keyword in ("AMAZON", "FLIPKART", "MYNTRA", "SWIGGY", "ZOMATO", "GROWW", "ZERODHA", "CRED", "JIO", "NETFLIX", "SPOTIFY"):
        if keyword in upper:
            return keyword.title()

    merchant_guess = _extract_merchant(text)
    return merchant_guess[:255]


def _clean_merchant_piece(piece: str) -> str:
    value = _normalize_space(re.sub(r"[^A-Z0-9& ]", " ", piece.upper()))
    for pattern in MERCHANT_NOISE_PATTERNS:
        value = _normalize_space(re.sub(pattern, "", value))
    value = value.replace("PETROL PU", "PETROL PUMP")
    value = value.replace("FILLING STATIO", "FILLING STATION")
    return _normalize_space(value)
