# Generated by Django 6.0 on 2026-03-12 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=50)),
                ('lender', models.CharField(blank=True, max_length=120)),
                ('principal', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('emi', models.FloatField()),
                ('tenure_months', models.PositiveIntegerField(default=12)),
                ('remaining_balance', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
