# Generated by Django 6.0 on 2026-03-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_ai_summary_expense_company_name_and_more'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('principal_component', models.FloatField(default=0)),
                ('interest_component', models.FloatField(default=0)),
                ('remaining_balance', models.FloatField(blank=True, null=True)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='auto_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='loan',
            name='missed_payments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('defaulted', 'Defaulted'), ('prepaid', 'Prepaid')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('car', 'Car Loan'), ('education', 'Education Loan'), ('business', 'Business Loan'), ('credit_card', 'Credit Card Debt'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'is_active'], name='loans_loan_user_id_1ef12b_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'),
        ),
        migrations.AddField(
            model_name='loanpaymenthistory',
            name='expense_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_loan_payments', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='loanpaymenthistory',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='loanpaymenthistory',
            index=models.Index(fields=['loan', 'payment_date'], name='loans_loanp_loan_id_6b589b_idx'),
        ),
    ]
