# Generated by Django 6.0 on 2026-03-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_transaction_fingerprint_and_more'),
        ('loans', '0002_loanpaymenthistory_loan_auto_detected_loan_closed_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanClosureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='loan_closures/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('closure_amount', models.FloatField(default=0)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='closure_reason',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='consolidated_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidated_loans', to='loans.loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='consolidation_group',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='loanpaymenthistory',
            name='detection_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loanpaymenthistory',
            name='detection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanpaymenthistory',
            name='match_status',
            field=models.CharField(choices=[('matched', 'Matched'), ('review', 'Needs Review')], default='matched', max_length=20),
        ),
        migrations.AddField(
            model_name='loanpaymenthistory',
            name='matched_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'consolidation_group'], name='loans_loan_user_id_7f1899_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpaymenthistory',
            index=models.Index(fields=['loan', 'match_status', 'payment_date'], name='loans_loanp_loan_id_e41735_idx'),
        ),
        migrations.AddField(
            model_name='loanclosuredocument',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_documents', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='loanclosuredocument',
            index=models.Index(fields=['loan', 'verification_status', 'created_at'], name='loans_loanc_loan_id_d8237a_idx'),
        ),
    ]
