# Generated by Django 6.0 on 2026-03-31 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanclosuredocument_loan_closure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanImportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='loan_imports/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=40)),
                ('parser_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_confidence', models.FloatField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_loans', models.ManyToManyField(blank=True, related_name='source_documents', to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_import_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'document_type', 'created_at'], name='loans_loani_user_id_9a8ebe_idx'), models.Index(fields=['user', 'parser_status', 'created_at'], name='loans_loani_user_id_6bfa44_idx')],
            },
        ),
    ]
