# Generated by Django 6.0 on 2026-04-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanclosuredocument_parser_status_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loanclosuredocument',
            new_name='loans_loanc_loan_id_b7f228_idx',
            old_name='loans_loanc_loan_id_6cf4a5_idx',
        ),
    ]
