# Generated by Django 6.0 on 2026-04-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0006_rename_loans_loanc_loan_id_6cf4a5_idx_loans_loanc_loan_id_b7f228_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("foreclosure_pending", "Foreclosure Pending"),
                    ("foreclosed", "Foreclosed"),
                    ("closed", "Closed"),
                    ("defaulted", "Defaulted"),
                    ("prepaid", "Prepaid"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LoanForeclosureSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("foreclosure_statement", "Foreclosure Statement"),
                            ("closure_letter", "Closure Letter"),
                            ("noc", "No Objection / No Due"),
                            ("loan_statement", "Loan Statement"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                ("lender_name", models.CharField(blank=True, max_length=120)),
                ("borrower_name", models.CharField(blank=True, max_length=180)),
                ("loan_account_number", models.CharField(blank=True, max_length=64)),
                ("statement_date", models.DateField(blank=True, null=True)),
                ("effective_closure_date", models.DateField(blank=True, null=True)),
                ("due_by_date", models.DateField(blank=True, null=True)),
                ("outstanding_principal", models.FloatField(default=0)),
                ("accrued_interest", models.FloatField(default=0)),
                ("foreclosure_charges", models.FloatField(default=0)),
                ("taxes_gst", models.FloatField(default=0)),
                ("overdue_charges", models.FloatField(default=0)),
                ("total_amount_payable", models.FloatField(default=0)),
                ("classification_confidence", models.FloatField(default=0)),
                ("linkage_confidence", models.FloatField(default=0)),
                ("linkage_notes", models.TextField(blank=True)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("unmatched", "Unmatched"),
                            ("partial_match", "Partial Match"),
                            ("full_match", "Full Match"),
                            ("mismatch", "Mismatch"),
                        ],
                        default="unmatched",
                        max_length=20,
                    ),
                ),
                ("reconciliation_confidence", models.FloatField(default=0)),
                ("matched_payment_total", models.FloatField(default=0)),
                ("matched_emi_transaction_ids", models.JSONField(blank=True, default=list)),
                ("matched_closure_transaction_ids", models.JSONField(blank=True, default=list)),
                ("reconciliation_notes", models.TextField(blank=True)),
                ("audit_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closure_document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foreclosure_snapshot",
                        to="loans.loanclosuredocument",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foreclosure_snapshots",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="loanforeclosuresnapshot",
            index=models.Index(fields=["loan", "document_type", "updated_at"], name="loans_loanf_loan_id_4b9d83_idx"),
        ),
        migrations.AddIndex(
            model_name="loanforeclosuresnapshot",
            index=models.Index(fields=["loan", "reconciliation_status", "updated_at"], name="loans_loanf_loan_id_3dc3c2_idx"),
        ),
    ]
