# Generated by Django 6.0 on 2026-04-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0007_alter_loan_status_loanforeclosuresnapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loanforeclosuresnapshot",
            new_name="loans_loanf_loan_id_b63179_idx",
            old_name="loans_loanf_loan_id_4b9d83_idx",
        ),
        migrations.RenameIndex(
            model_name="loanforeclosuresnapshot",
            new_name="loans_loanf_loan_id_a398c0_idx",
            old_name="loans_loanf_loan_id_3dc3c2_idx",
        ),
    ]
