# Generated by Django 6.0 on 2026-04-01 22:25

from django.db import migrations, models


def backfill_paid_components(apps, schema_editor):
    LoanPaymentHistory = apps.get_model("loans", "LoanPaymentHistory")
    for payment in LoanPaymentHistory.objects.all().iterator():
        payment.principal_paid = float(payment.principal_component or 0)
        payment.interest_paid = float(payment.interest_component or 0)
        payment.save(update_fields=["principal_paid", "interest_paid"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0008_rename_loans_loanf_loan_id_4b9d83_idx_loans_loanf_loan_id_b63179_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanpaymenthistory",
            name="charges_paid",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loanpaymenthistory",
            name="interest_paid",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loanpaymenthistory",
            name="penalties_paid",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loanpaymenthistory",
            name="principal_paid",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="loanpaymenthistory",
            name="tax_paid",
            field=models.FloatField(default=0),
        ),
        migrations.RunPython(backfill_paid_components, noop_reverse),
    ]
