# Generated by Django 6.0 on 2026-03-30 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('job_url', models.URLField()),
                ('apply_url', models.URLField(blank=True)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('job_title', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('fit_score', models.FloatField(default=0)),
                ('market_risk_score', models.FloatField(default=0)),
                ('strengths', models.TextField(blank=True)),
                ('gaps', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_job_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='career_care_user_id_0aee0d_idx'), models.Index(fields=['user', 'company', 'created_at'], name='career_care_user_id_8b566b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='career_resumes/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('parser_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_confidence', models.FloatField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='career_care_user_id_d0e86f_idx')],
            },
        ),
    ]
