# Generated by Django 6.0 on 2026-03-30 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_careerjobanalysis_careerresume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerResumeLearningMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_extension', models.CharField(max_length=16)),
                ('role_hint', models.CharField(blank=True, max_length=100)),
                ('skill_signature', models.CharField(blank=True, max_length=240)),
                ('successful_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_resume_learning_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['user', 'file_extension'], name='career_care_user_id_ffe2af_idx'), models.Index(fields=['user', 'role_hint'], name='career_care_user_id_754869_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'file_extension', 'role_hint', 'skill_signature'), name='career_resume_learning_memory_unique_key')],
            },
        ),
    ]
