# Generated by Django 6.0 on 2026-04-01 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_careerresumelearningmemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerjobanalysis',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='careerjobanalysis',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerjobanalysis',
            name='parse_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='careerjobanalysis',
            name='parser_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='careerjobanalysis',
            name='source_document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='careerjobanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='careerjobanalysis',
            index=models.Index(fields=['user', 'parser_status', 'updated_at'], name='career_care_user_id_d65d05_idx'),
        ),
    ]
