# Generated by Django 6.0 on 2026-03-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('expenses', 'Expenses'), ('loans', 'Loans'), ('career', 'Career'), ('mobility', 'Mobility'), ('risk', 'Risk'), ('behavioral', 'Behavioral'), ('reports', 'Reports'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField()),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reports_sys_status_f046e2_idx'), models.Index(fields=['module', 'status', 'created_at'], name='reports_sys_module_01853f_idx'), models.Index(fields=['user', 'created_at'], name='reports_sys_user_id_4d41a2_idx')],
            },
        ),
    ]
