# Generated by Django 6.0 on 2026-03-30 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_systemticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemticket',
            name='handled_by',
            field=models.CharField(choices=[('alfred', 'ALFRED'), ('developer', 'Developer')], default='developer', max_length=20),
        ),
        migrations.AddField(
            model_name='systemticket',
            name='resolution_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemticket',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddIndex(
            model_name='systemticket',
            index=models.Index(fields=['severity', 'handled_by', 'status', 'created_at'], name='reports_sys_severit_3c0c66_idx'),
        ),
    ]
