# Generated by Django 6.0 on 2026-03-31 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_systemticket_handled_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='general', max_length=30)),
                ('category', models.CharField(choices=[('document', 'Document Processing'), ('visualization', 'Visualization'), ('api', 'API'), ('background', 'Background Job')], default='document', max_length=20)),
                ('scope', models.CharField(blank=True, max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('document_id', models.PositiveIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'module', 'created_at'], name='reports_ope_user_id_360d9b_idx'), models.Index(fields=['user', 'scope', 'created_at'], name='reports_ope_user_id_6a9f14_idx'), models.Index(fields=['user', 'severity', 'created_at'], name='reports_ope_user_id_590a80_idx'), models.Index(fields=['category', 'created_at'], name='reports_ope_categor_1876bd_idx')],
            },
        ),
    ]
