# Generated by Codex on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_operationallog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGPTImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("import_type", models.CharField(choices=[("chat_transcript", "Chat Transcript"), ("dashboard_export", "Dashboard Export"), ("mixed_context", "Mixed Context")], default="chat_transcript", max_length=30)),
                ("source_label", models.CharField(blank=True, default="ChatGPT", max_length=120)),
                ("raw_text", models.TextField()),
                ("parsed_payload", models.JSONField(blank=True, default=dict)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(choices=[("review_ready", "Review Ready"), ("mapped", "Mapped"), ("archived", "Archived")], default="review_ready", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chatgpt_imports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "status", "created_at"], name="reports_cha_user_id_f5bb3e_idx"),
                    models.Index(fields=["user", "content_hash"], name="reports_cha_user_id_1c005f_idx"),
                    models.Index(fields=["import_type", "status", "created_at"], name="reports_cha_import__c2ac22_idx"),
                ],
            },
        ),
    ]
