# Generated by Django 6.0 on 2026-08-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_chatgptimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionProbeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_id', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['probe_id'], name='reports_pro_probe_i_8f4d80_idx'), models.Index(fields=['created_at'], name='reports_pro_created_795cc6_idx')],
            },
        ),
    ]
