# Generated by Django 6.0 on 2026-03-12 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('email', 'Email')], default='bank_statement', max_length=30)),
                ('original_file', models.FileField(blank=True, upload_to='statement_uploads/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('statement_start', models.DateField(blank=True, null=True)),
                ('statement_end', models.DateField(blank=True, null=True)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('classification', models.CharField(choices=[('expense', 'Expense'), ('loan', 'Loan'), ('other', 'Other')], default='expense', max_length=20)),
                ('category', models.CharField(choices=[('food', 'Food'), ('groceries', 'Groceries'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('fuel', 'Fuel'), ('health', 'Health'), ('subscription', 'Subscription'), ('entertainment', 'Entertainment'), ('rent', 'Rent'), ('loan', 'Loan / EMI'), ('credit_card', 'Credit Card Payment'), ('investment', 'Investment'), ('transfer', 'Transfer'), ('income', 'Income / Refund'), ('other', 'Other')], default='other', max_length=50)),
                ('payment_mode', models.CharField(default='UPI', max_length=50)),
                ('merchant', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_description', models.TextField(blank=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('bank_statement', 'Bank Statement'), ('email', 'Email')], default='manual', max_length=30)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('closing_balance', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_emotional', models.BooleanField(default=False)),
                ('model_confidence', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('statement_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.statementupload')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
