# Generated by Django 6.0 on 2026-03-30 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_ai_summary_expense_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'bank_account', 'transaction_date'], name='expenses_ex_user_id_a03f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'bank_account', 'transaction_fingerprint'], name='expenses_ex_user_id_a85cff_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'bank_account', 'external_reference', 'transaction_date'], name='expenses_ex_user_id_6daf8b_idx'),
        ),
    ]
