# Generated by Django 6.0 on 2026-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_transaction_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementupload',
            name='extracted_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='institution_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='parse_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='parser_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='statementupload',
            name='source',
            field=models.CharField(choices=[('bank_statement', 'Bank Statement'), ('credit_card_statement', 'Credit Card Statement'), ('loan_statement', 'Loan Statement'), ('investment_statement', 'Investment Statement'), ('other_statement', 'Other Statement'), ('email', 'Email')], default='bank_statement', max_length=30),
        ),
    ]
