# Generated by Django 6.0 on 2026-03-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavioral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='behavioralsignal',
            options={'ordering': ['-timestamp', '-id']},
        ),
    ]
